name: zego_uikit_prebuilt_call_local
description: PrebuiltCall is a full-featured call kit that provides a ready-made call invitation, voice/video chat, device detection, etc. Add a voice/video call to your app in minutes.
version: 1.4.2
homepage: https://www.zegocloud.com/

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_screenutil: ^5.5.3+2
  flutter_vibrate: ^1.3.0
  awesome_notifications: ^0.7.4+1
  audioplayers: ^1.0.1
  statemachine: ^3.2.0
  zego_uikit: ^1.9.1
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'

flutter:
  assets:
    - assets/icons/
    - assets/icons/img_collaboration.png
    - assets/invitation/audio/
    - assets/invitation/icons/
    - assets/invitation/icons/img_collaboration.png
